# coding=utf-8

from . import API_ROUTE_ALL_BUSES_HEADERS, API_ROUTE_ALL_BUSES_URL


# we pretend that individual routes are "cities" - the abstraction holds otherwise
CITIES = {
    '010': { 'of_interest': True },
    '099': {
        'of_interest': True
    },
    '020': {
        'of_interest': True
    },
    '005': {
        'of_interest': True
    }
}

# fill in data that can be assumed and autogenerated
for route_number, route_data in CITIES.items():
    if 'API_AVAILABLE_VEHICLES_URL' not in route_data:
        route_data['API_AVAILABLE_VEHICLES_URL'] = API_ROUTE_ALL_BUSES_URL(route=route_number)

    if 'API_AVAILABLE_VEHICLES_HEADERS' not in route_data:
        route_data['API_AVAILABLE_VEHICLES_HEADERS'] = API_ROUTE_ALL_BUSES_HEADERS
