#!/usr/bin/env python2
# coding=utf-8

from . import API_AVAILABLE_VEHICLES_URL, JSONP_CALLBACK_NAME


CITIES = {
    'montreal': {
    }
}

# fill in city data that can be assumed and autogenerated
for city, city_data in CITIES.items():
    city_data['of_interest'] = True  # we want everything for now

    if 'API_AVAILABLE_VEHICLES_URL' not in city_data:
        city_data['API_AVAILABLE_VEHICLES_URL'] = API_AVAILABLE_VEHICLES_URL(city)

    if 'JSONP_CALLBACK_NAME' not in city_data:
        city_data['JSONP_CALLBACK_NAME'] = JSONP_CALLBACK_NAME

KNOWN_CITIES = [
    city for city in CITIES]
# uncomment once we have map data - currently map tasks will fail, but we can still get stats
"""if ('BOUNDS' in CITIES[city]
        and 'MAP_LIMITS' in CITIES[city]
        and 'DEGREE_LENGTHS' in CITIES[city]
        and 'MAP_SIZES' in CITIES[city]
        and 'LABELS' in CITIES[city])
    ]"""
