#!/usr/bin/env python2
# coding=utf-8


CITIES = {
    'berlin': {
        'of_interest': True
    }
}


# from https://www.flinkster.de/kundenbuchung/process.php?proc=stadt&
# URL isn't quite right, but dealing with this API is a pain
# not sure if it's different cars than what Multicity has?


# fill in city data that can be assumed and autogenerated
for city, city_data in CITIES.items():
    if 'API_AVAILABLE_VEHICLES_URL' not in city_data:
        city_data['API_AVAILABLE_VEHICLES_URL'] = 'https://www.flinkster.de/kundenbuchung/hal2ajax_process.php?callback=testcallback'
