# coding=utf-8

from . import API_AVAILABLE_VEHICLES_URL


CITIES = {
    'milano': {
        'of_interest': True,
        'electric': 'all'
    }
}

# fill in city data that can be assumed and autogenerated
for city, city_data in CITIES.items():
    if 'API_AVAILABLE_VEHICLES_URL' not in city_data:
        city_data['API_AVAILABLE_VEHICLES_URL'] = API_AVAILABLE_VEHICLES_URL
